openapi: 3.0.4
info:
  title: Weather
  description: Weather is a simple tool for getting the current weather. It returns the temperature, humidity, and more for a given location.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/weatherforecast:
    get:
      summary: Get Current Weather by City
      description: Weather is a simple tool for getting the current weather. It returns the temperature, humidity, and more for a given location.
      operationId: weatherforecast
      parameters:
      - name: city
        in: query
        schema:
          type: string
        required: true
        description: The city for which you want to get the current weather (e.g., San Francisco)
        example: San Francisco
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  tempC: 15.6
                  tempF: 60.1
                  windMph: 4.9
                  windKph: 7.9
                  windDegree: 315
                  windDir: NW
                  pressureMb: 1021
                  pressureIn: 30.16
                  precipMm: 0
                  precipIn: 0
                  feelslikeC: 15.6
                  feelslikeF: 60.1
                  visKm: 16
                  visMiles: 9
                  gustMph: 6.6
                  gustKph: 10.5
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
